# -*- coding: utf-8 -*-
"""Goeduhub3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tnlfhyhOSCnMDsMKKtCB92mp9TNUPMcp

## Pandas
"""

pip install pandas

import numpy as np
import pandas as pd

a=np.array(['a','o','e','d','h','u','b'])
p=pd.Series(a)
print(p)

s1=pd.Series(np.random.random(6))
s1

s1=pd.Series(np.random.random(6),index=['a','b','c','d','e','f'])
s1

s1.dtype

type(s1)

data={'pi':3.14,'e':2.71}
print(data)

s3=pd.Series(data)
print(s3)

s=pd.Series(np.random.random(5))
print(s)

s[1]

s[1:3]

print(s.index)

print(s.size)

print(s.shape)

import numpy as np
import pandas as pd

df =pd.DataFrame({'Name':pd.Series(['Alice','Bob','Chris']),
                  'Age':pd.Series([21,25,23])
                  })

df

df['height']=pd.Series([5.2,6.0,5.6])

df

df=pd.read_csv("/content/Salaries.csv")

df

# top rows
df.head()

# bottom
df.tail()

df.shape

df.size

df.columns

df.dtypes

df.ndim

df.axes

type(df)

df1=df.values

type(df1)

"""## Basic Statistic"""

df.describe()

"""## Data Slicing and Grouping"""

df['phd']

df['service'].describe()

df['rank']

df_rank=df.groupby('rank')
df_rank

df_rank.mean()

"""## Mean salary for male and female"""

df1=df.groupby('sex')
df1

df1['salary'].mean()

df1[['salary']].mean()

df.groupby('rank',sort=False)[['salary']].mean()

"""## Filtering"""

df['salary']>160000
df_sub=df[df['salary']>160000]
df_sub

"""## Find the mean value of the salary for discipline A"""

df_disc=df[df['discipline']=='A']['salary'].mean()
df_disc

df_ch=df[df['salary']>100000].groupby('sex')[['salary']].count()
df_ch

"""## Slicing"""

df['salary']

df[['rank','salary']]

df[10:20]

df.iloc[10:20,[0,3,4,5]]

df.iloc[0]

df.iloc[:,1:3]

df.iloc[1:3,0:2]

df.loc[10:20,['rank','salary']]

"""## Sorting"""

df_sorted=df.sort_values(by='service')
df_sorted

df.sort_index(ascending=False)

df.sort_values(by=['service','salary'],ascending=[True,False])

"""## Aggregation Function"""

#agg
df.max()
df.min()

df[['service','salary']].agg(['min','mean','max'])

df.agg({'salary':['min','max','mean'],'service':['nunique']})

