# -*- coding: utf-8 -*-
"""Goeduhub2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJSTSmmPO4IxSWOxQ7t2kesInfQHybAT

# Numpy
"""

pip install numpy

import numpy as np

"""# Create 1-D Array"""

a=np.array([1,2,3])
print(a)
print(type(a))

"""# 2-D Array"""

a=np.array([[1,2,3],[10,20,30]])
print(a)
type(a)

np.zeros((2,3))

np.zeros((5,3))

np.arange(10)

np.arange(2,3,0.1)

np.arange(2,10)

np.linspace(1,4,6)

np.arange(1,4,6)

np.linspace(1,100)

np.linspace(1,100,num=4)

np.indices((3,3))

np.indices((5,4))

a=np.array([1,2,3])
print(a)

print(a.dtype)

"""# List vs numpy

## numpy array vs list memory allocation
"""

num

import numpy as np

# list
l=range(1000)
import sys
a=10
print(sys.getsizeof(a))
print(sys.getsizeof(a)*len(l))

#numpy
a1=np.arange(1000)
print(a1.size)
print(a1.size *a1.itemsize)

"""## numpy and list speed"""

import time
import sys

#list
size=1000000
l1=range(size)
l2=range(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

#numpy
n1=np.arange(size)
n2=np.arange(size)
start=time.time()
result1=n1+n2
print((time.time()-start)*1000)

"""# numpy operations"""

a=np.array([[1,2,3],[10,20,30]])
print(a)
print(a.ndim)

print(a.itemsize)

print(a.dtype)

a.shape

"""# Reshape"""

a

a.reshape(3,2)

"""# Slicing"""

a

a[0,0]

a[0,1]

a[0:,1]

a[1,1:]

a[0:,2]

a[0,1:]

a[0:2,1:]

a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
a

a.shape

a[1,2:4]

print(a.min())

print(a.max())

print(a.sum())

print(a)
print(np.sum(a,axis=0))

print(a)
print(np.sum(a,axis=1))

"""## Mathematical operation


"""

import numpy as np
x=np.array([[1,2],[4,5]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print(x + y)

print(np.add(x,y))

print(np.subtract(x,y))

print(x**2)
print(y**2)

a=np.arange(6)
a

a.reshape(3,2)

# another way
np.reshape(a,(2,3))

print(a)
np.reshape(a,6)

print(a.size)
print(a.reshape(3,2))

a.flatten()

