# -*- coding: utf-8 -*-
"""Goeduhub 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdXI6lbvMiNXidIKOLI7Vp55w2ySZVlz
"""

import pandas as pd
import numpy as np
dataset=pd.read_csv("/content/salaryData.csv")
dataset

dataset.columns

dataset.shape

dataset.info()

dataset.min()

dataset.max()

dataset.iloc[2:6]

dataset.tail()

dataset.corr()

dataset.nunique()

"""## Visualization using scatterplot"""

import matplotlib.pyplot as plt
x=dataset['YearsExperience']
y=dataset['Salary']
plt.plot(x,y,marker='+')
plt.xlabel('YearExperience')
plt.ylabel('Salary')
plt.show()

"""## Splitting of dataset into testing and training"""

x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,1].values
print(x)
print(y)

import sklearn
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=1/3,random_state=1)

"""## Creating Simple Linear Model"""

from sklearn.linear_model import LinearRegression
model=LinearRegression()

mymodel=model.fit(xtrain,ytrain)

"""## Prediction"""

y_pred=mymodel.predict(xtest)

y_pred

ytest

mymodel.coef_

mymodel.intercept_

plt.scatter(xtrain,ytrain,color='red')
plt.plot(xtrain,mymodel.predict(xtrain))
plt.show()

from sklearn.linear_model import LinearRegression
model=LinearRegression()

mymodel=model.fit(xtest,ytest)

plt.scatter(xtest,ytest,color='green')
plt.plot(xtest,mymodel.predict(xtest))
plt.show()

#y=mx+c
9158.13919873*6+26137.24001419694

import numpy as np
import matplotlib.pyplot as plt

a=0
b=0
rate=0.001
x=np.array([1,2,3,4,5])
y=np.array([5,8,11,14,17])
n=len(x)
plt.scatter(x,y,color='red')
for i in range(1000):
  y_pred=a*x+b
  cost=(1/n)*sum([value**2 for value in (y-y_pred)])
  print(a,b,i,cost)
  plt.plot(x,y_pred)
  ad=-(2/n)*sum(x*(y-y_pred))
  yd=-(2/n)*sum(y-y_pred)
  a=a-rate*ad
  b=b-rate*yd

