# -*- coding: utf-8 -*-
"""Numpy course .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUCcoKvjmO8axqTz5rvG-4F8rOkc9OU5

## Numpy
"""

# Numpy is a Python Library used for working Numerical Calculation and also working with array.
# It was created in 2005 by Travis Oliphant.
# It is open source and used freely
# It is written in c and c++.
# latest version 1.19.5

# Why Numpy and features:

# 1 High Performance
# 2 Integrated code
# 3 Multi Dimensional
# 4 Broadcasting Function
# 5 Work with varied database
# 6 Additional Linear Algebra

pip install numpy

# Use of Numpy:

# 1 Arithematic operation
# 2 Statistical
# 3 Bitwise
# 4 copying and viewing
# 5 stacking
# 6 searching
# 7 sorting
# 8 counting
# 9 Mathematical 
# 10 Broadcasting
# 11 Linear algebra
# 12 Matrix

import numpy as np

arr=np.array([1,2,3,4])
print(arr)

"""## or"""

from numpy import array
array=array([1,2,3,4])
print(array)

np.random.randint(2,10)

print(np.__version__)

sample=np.random.randint(0,10,2000)

# Commented out IPython magic to ensure Python compatibility.
# %timeit np.power(sample,2)

# Commented out IPython magic to ensure Python compatibility.
# %timeit list(np.power(sample,2))

"""## Dimension"""

import numpy as np
arr=np.array([1,2,3,4])
print(type(arr))

a=np.array(12)
print(a.ndim)

a=np.array([1,2,3,4])
print(a.ndim)

a=np.array([[1,2,3,4],[5,6,7,8]])
a.ndim

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.ndim

a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a.ndim

arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

"""## Shape"""

c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.ndim)

print(c.shape)

a=np.array([[1,2,3],[4,5,7]])
a.shape

a=np.array([[1,2,3],[5,6,7]])
a.shape=(3,2)

print(a)

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.reshape(2,3,2)

print(b)

a=b.reshape(-1)
a

a.dtype

a.itemsize

a.shape

a.size

a.size*a.itemsize

arr=np.array([1,2,3,4,5],dtype=complex)
arr

arr=np.array([1.1,2.2,3.3])
cv=arr.astype('i')
print(cv)

"""## name[start:stop:step]

# index
# slicing
"""

import numpy as np

arr=np.array([1,2,3,4,5,6])
arr[1]

arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr[0,1]

arr[1,4]

a=np.array([[[12,3,4,5,6],[7,6,5,4,3]],[[8,9,97,5,98],[56,34,23,12,34]]])
print(a[0,1,2])

a[1,-1]

b=np.array([[1,2,3,4],[5,6,7,8]])
b[1:]

b[1,-1]

c=np.array([1,2,3,4,5,6,7])
c[1:3]

c[4:]

b[:,2]

arr=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
arr[:,2]

arr[:,2]=[4000,5000]

arr

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,11,12]]])
arr

arr[0,1,2]

arr[:,1,:]

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,11,12]]])
arr[:,1,:]=[[9,9,9],[8,8,8]]

arr

arr=np.array([1,2,3,4,5,6,7])
arr[:4]

arr=np.array([1,2,34,5,6,77,8])
arr[-3:-1]

arr=np.array([1,2,3,4,5,6,7])
arr[1:5:2]

"""## Iter"""

import numpy as np

arr=np.array([1,2,3])
for x in arr:
  print(x)

arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
  print(x)

"""## Array"""

import numpy as np

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

arr2=np.arange(5)
print(arr2)

arr2=np.arange(10,20,2 ,dtype='float,')

arr2

arr3=np.linspace(10,20,5)
print(arr3)

arr3=np.linspace(10,20,5,endpoint=False)
print(arr3)

arr4=np.logspace(1.0,2.0,num=10)
arr4

"""## Zeros"""

import numpy as np

np.zeros(5)

np.zeros((2,3,4))

"""## ones"""

np.ones(5)

np.ones((4,2,2))

"""## full"""

np.full((2,2,2),99,dtype='int')

"""## full_like"""

arr=np.array([[1,2,3],[4,5,6]])
np.full_like(arr,4)

np.full(arr.shape,4)

"""## Identity"""

np.identity(5)

np.eye(5)

"""## repeat"""

arr=np.array([[1,2,3],[4,5,6]])
r=np.repeat(arr,3)
r

r=np.repeat(arr,3,axis=1)
r

"""## Empty"""

np.empty([3,2],dtype=int)

"""## Nan"""

x=np.array([12,32,np.nan])
x

"""## all"""

np.all([[True,False],[True,False]])

"""## any"""

np.any([[True,False],[True,False]])

"""## String Operation"""

import numpy as np

"""add"""

print(np.char.add(["Hallo"],["World"]))

print(np.char.add(["hello","hi"],["abc","xyz"]))

"""Multiply"""

print(np.char.multiply('hello',3))

"""Center"""

print(np.char.center('hello',20,fillchar='*'))

"""# **Capitalize**"""

print(np.char.capitalize('hello world'))

"""Title"""

print(np.char.title("hello world"))

"""lower"""

print(np.char.lower(["hello",'WORLD']))

"""JOIN"""

print(np.char.join(':','dmy'))

"""replace"""

print(np.char.replace('he is a good boy','is','was'))

"""## Statistical"""

import numpy as np

a=np.array([[3,7,5],[8,4,3],[2,5,7]])

a

np.min(a,1)

np.max(a,1)

np.ptp(a,axis=0)

np.ptp(a,axis=1)

np.percentile(a,50,axis=0)

np.percentile(a,75,axis=0)

np.mean(a,axis=0)

np.median(a,axis=0)

np.average(a)

np.std([1,2,3,4])

np.var([1,2,3,4])

"""## Random"""

import numpy as np

x=np.random.randint(100)

x

x=np.random.randint(100,size=(3,5))

x

x=np.random.rand(5)
x

x=np.random.choice([3,5,8,6])
x

x=np.random.choice([3,5,8,6],size=(3,5))
x

x=np.random.shuffle([1,2,3,4,5])
x

"""# Sort"""

import numpy as np

x=np.array([3,2,1,6])
np.sort(x)

a=np.array(['banana','cherry','apple'])
np.sort(a)

a=np.array([[3,4,8,7],[6,8,3,1]])
np.sort(a)

"""## search"""

import numpy as np

a=np.array([1,2,3,4,5,6,7,8,6,5,3,9])
x=np.where(a==5)
x

a=np.array([1,2,3,4,5,6,7,8,6,5,3,9])
x=np.where(a%2==1)
x

a=np.array([1,2,3,4,5,6,7,8,6,5,3,9])
x=np.where(a%2!=1)
x

a=np.array([1,2,3,4,5,6,7,8,6,5,3,9])
x=np.searchsorted(a,11,side='right')
x

"""## split"""

import numpy as np

a=np.array([1,2,3,4,5,6])
np.array_split(a,3)

a=np.array([1,2,3,4,5,6])
np.array_split(a,4)

"""## Join"""

import numpy as np

a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.concatenate((a1,a2))

arr

a1=np.array([[1,2],[3,4]])
a2=np.array([[4,5],[7,8]])
arr=np.concatenate((a1,a2),axis=1)

arr

a1=np.array([[1,2],[3,4]])
a2=np.array([[4,5],[7,8]])
arr=np.concatenate((a1,a2),axis=0)

arr

a1=np.array([[1,2],[3,4]])
a2=np.array([[4,5],[7,8]])
arr=np.stack((a1,a2),axis=0)

arr

a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.vstack((a1,a2))

arr

a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.hstack((a1,a2))

arr

a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.dstack((a1,a2))

arr

"""## Numpy with files"""

import numpy as np

a=np.array([1,2,3,4,5])
np.save('outfile',a)

b=np.load('outfile.npy')
b

"""## Matplotlib with numpy"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(1,11)
y=2*x+5

plt.title("demo")
plt.xlabel("X Axix")
plt.ylabel("Y Axis")
plt.plot(x,y,'ob')
plt.show()

x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)

plt.plot(x,y)
plt.show()

